version: "3.7"
services:
  myservice:
    image: kethansrinivas9/services
    environment:
      - MACHINE_IP=${MACHINE_IP}
    ports:
      - "3000:3000"
    depends_on:
      - log
      - catalogue
      - notes
  catalogue:
    image: kethansrinivas9/catalogue
    ports:
      - "3001:3001"
  log:
    image: kethansrinivas9/log
    ports:
      - "3002:3002"
  notes:
    image: kethansrinivas9/notes
    ports:
      - "3003:3003"